spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mtoken?useUnicode=true&characterEncoding=utf8&mysqlEncoding=utf8
    username: root
    password: password
    tomcat:
      initialSize: 1
      min-idle: 1
      max-idle: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
logging:
  file: logs/demo.log
mybatis:
    type-aliases-package: com.zjft.entity
    mapper-locations: classpath:mapper/*.xml